config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
      # user.oath_token = auth['info']
      user.oauth_token = auth['credentials']['token']
      user.oauth_secret = auth['credentials']['secret']
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?
  helper_method :config_twitter

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

    def config_twitter
        $client = Twitter::REST::Client.new do |config|
        config.consumer_key        =  ENV["OMNIAUTH_PROVIDER_KEY"] 
        config.consumer_secret     =  ENV["OMNIAUTH_PROVIDER_SECRET"]
        config.access_token        = current_user.oauth_token
        config.access_token_secret = current_user.oauth_secret
      end
    end


    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'



  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :config_twitter
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    @twitter_user = $client.user

    @followers_count = @twitter_user.followers_count

    @friends_count = @twitter_user.friends_count

    @statuses_count = @twitter_user.statuses_count

    # @trends = $client.trends_available

    @profile_image = @twitter_user.profile_image_url

  end

  def new_tweet
  	$client.update("test tweet")
  end




end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <%= image_tag(@profile_image, class: "profile_image")%>

    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Omniauth" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Omniauth" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">



	<div class="col-md-4 ">
		<div class="panel panel-default">	
		  	<div class="panel-body lightblue">
		    	<div class="panel-icon">
		    		<%= fa_icon "users 5x" %>
		    	</div>	
		    	<div class="icon-text">
		    		<p class="number"><%= @followers_count %></p><p> followers</p>
		    	</div>
		    
		  	</div>

		  <div class="panel-footer ">
		  	More info
		  </div>
		</div>
	</div>

	<div class="col-md-4 ">
		<div class="panel panel-default">	
		  	<div class="panel-body green">
		  		<div class="panel-icon">
		    		<%= fa_icon "twitter 5x" %>
			  	</div>
			    <div class="icon-text">
			    	<p class="number"><%= @statuses_count %></p><p> tweets</p> 
			    </div>
		    </div>
		  	<div class="panel-footer ">
		  		More info
		  	</div>
		</div>
	</div>

	<div class="col-md-4 ">
		<div class="panel panel-default">	
			<div class="panel-body pink">
				<div class="panel-icon">
				    <div id="big-user"><%= fa_icon "user 5x" %></div>
				    <div id="arrow-right"><%= fa_icon "level-up 2x" %></div>
				    <div id="small-user"><%= fa_icon "user 3x" %></div>
				</div>
				<div class="icon-text">
					<p class="number"><%= @friends_count %></p><p> users you follow</p> 
			    </div>
			</div>
		  <div class="panel-footer ">
		  	More info
		  </div>
		</div>
	</div>



<!--  fa-users [&#xf0c0;]
 fa-twitter [&#xf099;] -->

</container>

<!-- http://jsonviewer.stack.hu/ -->

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>